// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function CalculatePromptCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculatePromptCost'](arg1, arg2, arg3);
}

export function CountGeminiTokens(arg1) {
  return window['go']['main']['App']['CountGeminiTokens'](arg1);
}

export function ExecuteGeminiRequest(arg1, arg2) {
  return window['go']['main']['App']['ExecuteGeminiRequest'](arg1, arg2);
}

export function GetCustomIgnoreRules() {
  return window['go']['main']['App']['GetCustomIgnoreRules']();
}

export function GetCustomPromptRules() {
  return window['go']['main']['App']['GetCustomPromptRules']();
}

export function GetGeminiAPIKey() {
  return window['go']['main']['App']['GetGeminiAPIKey']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function RequestShotgunContextGeneration(arg1, arg2) {
  return window['go']['main']['App']['RequestShotgunContextGeneration'](arg1, arg2);
}

export function ResetApplication() {
  return window['go']['main']['App']['ResetApplication']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCustomIgnoreRules(arg1) {
  return window['go']['main']['App']['SetCustomIgnoreRules'](arg1);
}

export function SetCustomPromptRules(arg1) {
  return window['go']['main']['App']['SetCustomPromptRules'](arg1);
}

export function SetGeminiAPIKey(arg1) {
  return window['go']['main']['App']['SetGeminiAPIKey'](arg1);
}

export function SetUseCustomIgnore(arg1) {
  return window['go']['main']['App']['SetUseCustomIgnore'](arg1);
}

export function SetUseGitignore(arg1) {
  return window['go']['main']['App']['SetUseGitignore'](arg1);
}

export function SplitShotgunDiff(arg1, arg2) {
  return window['go']['main']['App']['SplitShotgunDiff'](arg1, arg2);
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StartupTest(arg1) {
  return window['go']['main']['App']['StartupTest'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}

export function StopGeminiRequest() {
  return window['go']['main']['App']['StopGeminiRequest']();
}
